export const names = {
	bg: {
		0: "blank",
		1: "grass",
		2: "grass_flowery",
		3: "bricks",
		4: "school_plank",
		5: "school_plank2",
		6: "gradient_top",
		7: "gradient_bottom",
		8: "school_wall_up",
	},
	fg: {
		0: "blank",
		1: "test_object",
		2: "table",
		3: "chair_down",
		4: "chair_right",
		5: "chair_left",
		6: "chair_up",
		7: "locker_right",
		8: "locker_double",
		9: "locker_left",
		10: "locker_fallA",
		11: "locker_fallB",
		12: "locker_hang",
		13: "locker_missing",
		14: "floor3_railing_horizontal",
		15: "floor3_railing_turn_right",
		16: "floor3_railing_vertical",
		17: "floor3_railing_turn_left",
		18: "fallen_debrisA",
		18.1: "fallen_debrisB",
		18.2: "fallen_debrisC",
		18.3: "fallen_debrisD",
	},
	items: { // [internal, display]
		0: ["blank", ""],
		1: ["test_item", "James Ree"],
	}
} as const;
